VERSATILEPB_GPIOD_OBJS = $(ROOT_DIR)/sbin/dev/arch/versatilepb/gpiod/gpiod.o

VERSATILEPB_GPIOD = $(TARGET_DIR)/$(ROOT_DIR)/sbin/dev/versatilepb/gpiod

PROGS += $(VERSATILEPB_GPIOD)
CLEAN += $(VERSATILEPB_GPIOD_OBJS)

$(VERSATILEPB_GPIOD): $(VERSATILEPB_GPIOD_OBJS) $(LIB_OBJS)
	$(LD) -Ttext=100 $(VERSATILEPB_GPIOD_OBJS) $(LIB_OBJS) -o $(VERSATILEPB_GPIOD) $(LDFLAGS)
